### ISSUE TITLE
Do not panic - return error instead

### ISSUE THREAD

**Issue by krhubert** [tendermint/tm-db#28] opened 2019-11-08 19:14 UTC
Hi,

Can db methods be changed so they return error instead of panic. It will help a lot in handling error case without repeting `recovery` everywhere.

**Comment by marbar3778** [comment] 2019-11-08 22:06
this is a duplicate of https://github.com/tendermint/tm-db/issues/4, we have this in mind just haven't gotten around to doing it. We do welcome prs and will review them as soon as possible once they come in 😄

**Closed** 2019-12-11 12:27 UTC
